### ISSUE TITLE
Max quality set on server not respected

### ISSUE THREAD

**Issue by soloam** [faush01/plugin.video.embycon#102]
Hello, I noticed that the max quality that I set in the server is not respected in EmbyCon even in http streaming. The user is able to select any quality even direct play at full quality. On my server I have limits set to quality on user level, and server level, and on kodi they are able to stream at any quality, even superior to the one that I have set as max.

Thank You

**Comment by faush01** [comment]
Do you mean this setting?
"Internet streaming bitrate limit (Mbps):"
If so I am not sure this is applied to all clients.
I have asked the question on the forums:
https://emby.media/community/index.php?/topic/87355-internet-streaming-bitrate-limit-mbps/

**Comment by soloam** [comment]
Yes that setting!

Thank you

**Comment by faush01** [comment]
After looking at this for a few days I dont think EmbyCon is going to be able to enforce this server side setting.
EmbyCon constructs its streaming URLs manually and thus bypasses any server logic put in place for this.
It would require a complete rewrite of the playback logic and remove some of the control from the client and pass it back to the server.
For now until I can work out a better way this will have to stay as unsupported.

**Comment by faush01** [comment]
I have added support for this to the latest beta.
Can you test the latest beta and see if this limit is now enforced for your users.

**Comment by soloam** [comment]
I'll test it out tomorrow and give some feedback! Thank you

**Comment by faush01** [comment]
did you get a chance to test this?

**Comment by faush01** [comment]
closing this for now, if anyone finds any issues we can reopen.
