### ISSUE TITLE
Jellyfin compat broken

### ISSUE THREAD

**Issue by mcarlton00** [faush01/plugin.video.embycon#104]
A recent reddit post mentioned that Embycon was no longer working on their Jellyfin server.  I traced it back to https://github.com/faush01/plugin.video.embycon/commit/867545a9b34bb8b456ff78a19b228b633ae39992.  Jellyfin doesn't provide the `DirectStreamUrl` and `TranscodingUrl` values in their item payload.

I've poked at it a bit and have a few ideas, but wanted to reach out and see if there was interest on your side to work together on keeping this going.  It is a bit of extra overhead to have both, so I understand if you'd rather not.  We always knew the day would come that the APIs would begin to diverge, we just always assumed it was going to come from the JF side, not the Emby side.

Potential ways forward:
1. We can store the results of `{server}/system/info/public` (possibly in the settings dialog, or a variable that can be referenced easily).  It contains a ProductName key that will determine whether it's Emby or Jellyfin.  Then when `get_play_url()` is called it can check that and determine how to build the URL.
2. Expand the logic inside of `get_play_url()` to fallback to a separate method that works for JF.  Change https://github.com/faush01/plugin.video.embycon/blob/14514fc7b5831e9eeff467267a527927488c503e/resources/lib/utils.py#L99 to 
```python
direct_stream_path = media_source.get("DirectStreamUrl")
if not direct_stream_path:
    # build URL for JF
else:
    direct_stream_path = server + "/emby" + direct_stream_path
```
and do similar for the transcoding bits.

I'm not familiar with the codebase here, those are just the two methods I've thought of so far.

**Comment by faush01** [comment]
This might be a good time to fork the project.
As you mentioned the two servers will diverge at some point and now is probably as good a time as any to fork and have a Jellyfin version if there is someone that wants to take that up.

**Comment by mcarlton00** [comment]
Yeah, that thought had crossed my mind.  I can't say that I _want_ to take on a second addon, but it might be the right answer at this point.  I should have a good bit of time this weekend to look into things and hopefully figure out a way forward.

**Comment by faush01** [comment]
I think that a fork will be the best way forward, I get the feeling the APIs will diverge more and more now and having to keep the login in one addon is going to cause for issues than it is worth.

**Comment by mcarlton00** [comment]
I've forked this over to https://github.com/mcarlton00/jellycon and (hopefully) fixed the URL generation errors.  If you get anymore Jellyfin related issues from users feel free to send them my way

**Comment by faush01** [comment]
Cool will do, thanks.
