### ISSUE TITLE
Video file looks like it will start to play then stops

### ISSUE THREAD

**Issue by seegee99** [faush01/plugin.video.embycon#105]
Selecting a video file in EmbyCon, it will appear to start loading, but then there is no playback.  It takes between 1-20 times clicking the file before it loads.  When selecting a file that I've already started, it will do the same thing, except it will restart the resume pointer.  It's especially frustrating to lose the resume point and have to scrub to get to the same general location.

I've tried in Chrome and LG's Emby client with no issues, playing back the first time, every time.

**Comment by faush01** [comment]
will need a log file:

- turn on debug loggin in the EmbyCon settings under advanced
- restart Kodi
- reproduce the issue
- shut down kodi
- send me the log (easiest way is upload the log to pastbin or similar and post the link)

**Comment by faush01** [comment]
Without a log this can not be diagnosed.

**Comment by seegee99** [comment]
Sorry for the late reply.  It was fixed, and it had to do with files with subtitles.  Thanks!
