### ISSUE TITLE
Feature Request: Connection limit

### ISSUE THREAD

**Issue by seegee99** [faush01/plugin.video.embycon#106]
I have a connection to a shared server that is limited to 1 simultaneous connection.   Can a feature be added where it will stop the currently playing video before starting a new video?  Otherwise an error pops up that I have exceeded my connection limit.

Thank you so much.

**Comment by faush01** [comment]
How are you playing the next video?

**Comment by seegee99** [comment]
I was hoping to use the Up Next add-on.  I tried the feature request there, but was referred here.

**Comment by faush01** [comment]
use the built in play next feature of EmbyCon, it will offer to play the next episode if there is one.

**Comment by seegee99** [comment]
Can it be set to automatically play the next episode?

**Comment by faush01** [comment]
Yes, set it to don't prompt

**Comment by seegee99** [comment]
I'll have to try it.  It's not quite as slick as having the countdown timer with options, but it could work.

**Comment by faush01** [comment]
What countdown timer?
