### ISSUE TITLE
No plugin.video.embycon Upadte over repository.emby.kodi-1.0.6.zip  

### ISSUE THREAD

**Issue by Ron801** [faush01/plugin.video.embycon#107]
Hi. I was waiting few whiles for an repo Update. So was looking here at plugin.video.embycon github and saw there is an Update available
Please can you explain, why no updates over the repos comeing?

My last version was plugin.video.embycon 1.9.82 from Team B

**Comment by faush01** [comment]
You are using the stable repo (repository.emby.kodi-1.0.6.zip)
This repo has fewer releases and only has new releases when current test releases to the Beta repo become stable.
The last update to STABLE was 20 June.

The next release to STABLE will be in the next week or so when the current BETA has reached the stable status.

STABLE mean the beta has had no new bug reports or issues for a few weeks.
