### ISSUE TITLE
https streams aborting

### ISSUE THREAD

**Issue by lukkie112** [faush01/plugin.video.embycon#108]
Hello!

Sorry for my bad english

I am using EmbyCon few month with "http" Connection without problems

Now I have to use "https" instead of "http" to connect to my Server, because http is for me not available any more

Connection to Server is no Problem
Streams are starting without problems but during streaming, streams abort/stops

Than I can push play and stream starts on the position, where the stream aborted

I have testet some EmbyCon Settings, but nothing helps

Please can you tell me what the problem is

Fore excample some Hardware Sytstems with this issue:

FireTV1 / Kodi18.7 / EmbyCon stable
nvidia shield 2017 / Kodi 18.6 / embycon stable 
nvidia shield pro / kodi 18.8 / Embycon stable
xioami Mi Box / kodi 18.7 / embycon stable

**Comment by faush01** [comment]
I dont think this is HTTPS related, you should post over on the Emby forums to try to get help with the server connection.
https://emby.media/community/
