### ISSUE TITLE
Recently Embycon keeps asking to clone the default skin every bootup

### ISSUE THREAD

**Issue by daveftw84** [faush01/plugin.video.embycon#112]
Recently Embycon keeps asking to clone the default skin every bootup

**Comment by faush01** [comment]
just let it clone it, you dont have to use it.

**Comment by faush01** [comment]
Perhaps this approach of trying to clone the default skin is not the best approach.
I might create a new skin and put it in the repo and add it as a requirement of the addon, this way it is using the standard Kodi way of doing things.

**Comment by daveftw84** [comment]
It freezes, can you just have it maybe ask once

**Comment by faush01** [comment]
I have rolled the change back, it should never ask this again.
I have made a custom skin addon that can be used instead of having to clone the default skin.

**Comment by daveftw84** [comment]
Awesome, thanks!
