### ISSUE TITLE
Remote play command: StartPositionTicks do not work when sending multiple ItemIds

### ISSUE THREAD

**Issue by puenktchen** [faush01/plugin.video.embycon#113]
Hi,
When sending multiple ItemIds with the remote play command of Emby's SessionsService,
the StartPositionTicks has no affect in Kodi. It works correctly with a single ItemId though.
Is it possible for you to correct this?
Maybe by just start playing the StartIndex item the normal way and then
queueing the remaining items to Kodi's video player/playlist?

**Comment by faush01** [comment]
From memory this was the only way I could get this to work when playing a playlist with multiple items.
there is a multiple play function:

https://github.com/faush01/plugin.video.embycon/blob/4b36f08c70853e8814101afd1c37d5576f98a8cb/resources/lib/play_utils.py#L31

And it just builds the playlist and plays it, from memory it would not work if I tried top edit the playlist after playback started or if I tried to skip the current item to a location.

**Comment by puenktchen** [comment]
I think you nearly have all necessary methods in place and only "some smaller" changes are needed. It starts with:
https://github.com/faush01/plugin.video.embycon/blob/4b36f08c70853e8814101afd1c37d5576f98a8cb/resources/lib/play_utils.py#L218 If it is a list of items in "play_file", play the start index and
add all the rest to a home property with a param "play_items=false", so that later in https://github.com/faush01/plugin.video.embycon/blob/4b36f08c70853e8814101afd1c37d5576f98a8cb/resources/lib/play_utils.py#L31 it starts not playling the list, but just returns the playlist. The home property should be evaluated by your service monitor https://github.com/faush01/plugin.video.embycon/blob/4b36f08c70853e8814101afd1c37d5576f98a8cb/resources/lib/play_utils.py#L1117 that should be extended with [onAVStarted()](https://codedocs.xyz/AlwinEsch/kodi/group__python___player_c_b.html#ga61cb60571b974e447dba57bdaa77aace) to call "play_all_files".
onAVStarted ensures there's actually a stream playing, otherwise add something to the current video playlist could fail.

**Comment by faush01** [comment]
The main problem is there does not appear to be a way of indicating if you want to resume when playing a list of items.
If you select in the Web Client a season and then select play all, there is no resume option, the list is sent to the client.
The client then assumes there is no resume requested and just plays the list of items form the beginning even if the first item was partially played.

The two options are:
 - Assume they want to resume the first item is partially played when playing a list of items, if the first item in the list is partially played then jump to current progress offset when you start playback
 - Assume they want to play all items from the beginning

I Picked the second one

**Comment by puenktchen** [comment]
> If you select in the Web Client a season and then select play all, there is no resume option, the list is sent to the client.
> The client then assumes there is no resume requested and just plays the list of items form the beginning even if the first item was partially played.

Probably because the Emby devs also assume your second option here and just never send the resume point as StartPositionTicks. But if the StartPositionTicks are there the Emby clients behave correctly. I need the first option to achieve with EmbyCon the same as with other Emby clients. That is to mimic real live tv with normal library items in my VirtualTV plugin for Emby.

**Comment by faush01** [comment]
not sure what you mean by mimic real live tv, as I said it would just start playback at the resume point of the first item.

**Comment by puenktchen** [comment]
The start item actually doesn't have a resume point. I just send the difference between the current time of channel switching and the program start time of the guide data as StartPositionTicks.

**Comment by faush01** [comment]
So this message is not sent by the emby web client or native emby system, it is triggered by a custom plugin?

**Comment by puenktchen** [comment]
Correct.

**Comment by faush01** [comment]
ok, perhaps if I have a look at the source and see what is being sent that will help me understand what is needed. Where is the plugin source?

So is it sending playlists of actual LIVE TV or just playlists of items in the user collection.

**Comment by puenktchen** [comment]
> ok, perhaps if I have a look at the source and see what is being sent that will help me understand what is needed. Where is the plugin source?
> 
> So is it sending playlists of actual LIVE TV or just playlists of items in the user collection.

It's sending a list of items of the user's library:

```
var playRequest = new PlayRequest
{
    ControllingUserId = sessionInfo.UserId,
    ItemIds = listItems.ToArray(),
    StartIndex = startIndex,
    StartPositionTicks = startOffset, //<-This is what this is all about
    PlayCommand = PlayCommand.PlayNow
};

Emby.SessionManager.SendPlayCommand(sessionInfo.Id, sessionInfo.Id, playRequest, cancellationToken);
```

**Comment by faush01** [comment]
So I need to pass StartPositionTicks all the way through to the play_all_files action and "assume" this is the offset in the first item.
Yes I think that can be done. It will be hard for me to test it tough.

**Comment by puenktchen** [comment]
You can use Swagger for testing. That's what i do.

**Comment by faush01** [comment]
How can i simulate a remote control action of play multiple items with a start offset using swagger?

**Comment by puenktchen** [comment]
First take note of two or three ItemIds by browsing the details screen of some movies:

![ItemId](https://user-images.githubusercontent.com/1786629/125315622-9a844c00-e337-11eb-8255-8d68e3d707c0.PNG)

Then in Swagger take note of the SessionId and UserId that is listed for your EmbyCon Session:

![SessionId UserId](https://user-images.githubusercontent.com/1786629/125315689-a7a13b00-e337-11eb-9578-ce31539587bd.PNG)

Finally fill out the session play command with StartPositionTicks=9000000000 [(Online converter - 15 minutes)](https://www.venea.net/web/net_ticks_timespan_converter#time_span_to_net_ticks_conversion)

![PlayCommand](https://user-images.githubusercontent.com/1786629/125316161-25fddd00-e338-11eb-8b93-6131985cae7c.PNG)

**Comment by faush01** [comment]
I added this to the latest beta 1.9.116 for Kodi 18
I could not fully test it but was able to get it to work by injecting data directly into the activity

**Comment by puenktchen** [comment]
Working great so far! But please give me some more days to test it on my production system.

**Comment by puenktchen** [comment]
I have nothing to complain. Extra ordinary work from your side. Thank you so much!
