### ISSUE TITLE
Playback stop command is missing LiveStreamId for live tv channels

### ISSUE THREAD

**Issue by puenktchen** [faush01/plugin.video.embycon#114]
The Sessions/Playing/Stopped command that EmbyCon is sending to Emby is missing the LiveStreamId for live tv channels.
Without that LiveStreamId Emby never closes the tuner, at least with live tv plugins.

**Comment by faush01** [comment]
Is this something new? I dont remember this being needed.

**Comment by puenktchen** [comment]
> Is this something new?

I don't think so, but there are different ways to open a live tv stream that need different ways to stop:
One is 
- send post to **Items/{ChannelId}/PlaybackInfo** with "AutoOpenLiveStream=true"
- get from response "LiveStreamId", "DirectStreamUrl" if existing otherwise "TranscodedStreamUrl"
- start playing by calling "DirectStreamUrl"
- stop playing by sending post to **Sessions/Playing/Stopped** with at least "ItemId" and "LiveStreamId"

PlaySessionId is only used for normal video items, so not needed but it doesn't hurt

The other way is
- directly call **Videos/{ChannelId}/stream?Static=true** without any "LiveStreamId"

No prior call to PlaybackInfo is needed but it only works for a direct stream, not when transcoding is needed
No post to **Sessions/Playing/Stopped** is needed here, the stream just stops if the player disconnects

**Comment by faush01** [comment]
This sounds like it would require a re write of the playback URL code.

**Comment by faush01** [comment]
If Emby requires this I dont think EmbyCon can support Live TV.

I remember testing a few live TV WEB channels a long time ago when I implemented it and it was working but I dont have a live tv source to test with so can not comment on if it actually works with Live TV or not.

**Comment by puenktchen** [comment]
> If Emby requires this I dont think EmbyCon can support Live TV.

Why? I don't understand. You already get the LiveStreamId from the PlaybackInfo response and you are even using it with Videos/{ChannelId}/stream.ts which is generally okay, because of the playback capabilities of Kodi it's the same as the DirectStreamUrl of the PlaybackInfo. You just have to use that LiveStreamId as additional parameter in your Session/Playing/Stopped. That's really all you need to change.

**Comment by faush01** [comment]
Ok, I will see what is required to pass this along to the stop of a playback item.

**Comment by faush01** [comment]
this should be added in the latest Beta build for Kodi 18

**Comment by faush01** [comment]
version 1.9.116

**Comment by faush01** [comment]
I can not test this at all, I dont have live stream sources, I never see the LiveStreamId in any of my requests to PlaybackInfo

**Comment by faush01** [comment]
Do a pull request if you want, or just send me the updated file and i can merge it in

**Comment by faush01** [comment]
I have manually merged your changes to develop.
I dropped the commenting out of stop all on playback as it is still needed.

**Comment by faush01** [comment]
in beta 1.9.118 for Kodi 18

**Comment by puenktchen** [comment]
> I dropped the commenting out of stop all on playback as it is still needed.

Can you please explain the reason of sending stop right after playback has started? In case of live tv, it will actually stop the stream/tuner that was opened before by AutoOpenLivestream from the PlaybackInfo request! Thus the following playback will fail. I didn't notice any problems without the stop command.

**Comment by faush01** [comment]
It had something to do with playing a new item without stopping the running item. The playback stopped event would not trigger so the server would not know the old item had stopped.

**Comment by puenktchen** [comment]
If Kodi crashes or something like that? It's the same with the Emby apps. If the Emby apps crash, no stop command is send. The server should handle this scenario not the client and i think it does nowadays. I will test and report back.

**Comment by puenktchen** [comment]
What about this one: https://github.com/puenktchen/plugin.video.embycon/commit/69c55dd661f0a1678d29e2b41da49b8c6dd051f0 ?
It's more logical to stop any previous stream that is still running, instead of the one we want to play now.
This works fine for me. I've tested it by disabling onPlayBackEnded() and onPlayBackStopped(). When a new stream is about to start, the previous one gets killed, but not the new one.

**Comment by faush01** [comment]
Send me your play_utils file and i will run some tests

**Comment by faush01** [comment]
This was not due to a Kodi crash or client crash. From memory the original problem was onPlayBackStopped(self) was not called when a user played a new file without stopping the old one, this left the current item being played or in the play state on the Emby server and also did not trigger and stop playback activity that was needed in the Stop Playback action of the plugin.

Just testing now it looks like the original Kodi issue may have been fixed and the onPlayBackStopped(self) is correctly being called now when a user selects a new item to play without stopping the currently playing item.

This mean this call in may not be necessary at all any more.

However it should not be Stopping your session as the **stop_all_playback** has this check
if data.get("currently_playing", False) is True:
so any playing item that has not yet started will not be stopped.
I think your issues is with these lines from the **stop_all_playback** 
`    
    device_id = ClientInformation().get_device_id()
    url = "{server}/emby/Videos/ActiveEncodings?DeviceId=%s" % device_id
    download_utils.download_url(url, method="DELETE")
`
I think this might be killing your Live Stream Encoding.

Anyway I think it might be safe to stop calling the stop_all_playback when a playback starts.

**Comment by puenktchen** [comment]
Thanks for your detailed explanation. And your probably right with "ActiveEncodings".  It's up to you how to move on. Either put the stop command into playback start or just leave it out of onPlaybackStarted like you did in your last commit. Both is working fine for me. Thank you again!
