### ISSUE TITLE
Waking from sleep with a stream playing breaks Kodi

### ISSUE THREAD

**Issue by juanma-cvega** [faush01/plugin.video.embycon#120]
I'm currently using an Nvidia Shield 2019 pro plugged to a TV. If I put the device to sleep while watching a stream, either by stopping it and letting it go to sleep or by switching off the TV, next time the Shield wakes up, Kodi crashes after a few seconds. I tried this with other addons and it doesn't happen. Is there any setting that prevent this from happening?
Thanks.

**Comment by faush01** [comment]
no setting that I know of, the addon just gets Kodi to play a stream, it does not do anything that most other addons are doing.
you could try tuning off the event actions in the addon settings, it might help but that is guest a guess.

**Comment by juanma-cvega** [comment]
I tried that but it's still failing. Anyway, I found another plugin that has the same problem so it seems it is Kodi related. Closing now.
