### ISSUE TITLE
Subtitles force transcoding

### ISSUE THREAD

**Issue by juanma-cvega** [faush01/plugin.video.embycon#121]
For the past months I've been having issues with some videos that demand selecting a subtitle from the list of available ones before start playing (sometimes this also happens with the sound track) when before it didn't. After selecting the subtitle, I can see the video is being transcoded because of it. When using the native Emby application I don't have this problem and I can select whatever subtitle I want that the stats always say direct play. 
I'm using a Nvidia Shield 2019 Pro which I think should be able to manage any subtitle format, same with Kodi.

**Comment by juanma-cvega** [comment]
But in this case it doesn't need to. And I can see this when I use the native android app. Actually, it fails to play the video if I choose any of the subtitles, I guess because the server is not able to add the subtitle to the video. Is this a server setting or could it be controlled from the client? And even in the case I choose none as subtitle, it still transcodes the video.

**Comment by faush01** [comment]
i don't know why it is transcoding. Its not possible to tell without looking at the logs and the video media in question.

**Comment by juanma-cvega** [comment]
I got some logs from Kodi. I pasted them [here](https://pastebin.com/GBabu9Ja). 
I can see that at some point it says transcoding because of a subtitle codec not supported. But I don't get any errors while using the native android client. Is there any way transcoding could be avoided or is the server that handles this? Maybe a setting in the server configuration?

**Comment by faush01** [comment]
I have the logs and looking at this, there is a little bit of discussion in the following thread:
https://emby.media/community/index.php?/topic/110849-subtitle-support-in-deviceprofile-post-action/

**Comment by juanma-cvega** [comment]
Hi, thanks for looking into this.
So as far as I undestand, the first test would be to add the subrip type of subtitles into the subtitle profiles that is controlled within the addon, right? About the extracting the subtitles on the fly solution, I don't manage this server and this problem started to happen suddenly so maybe the setting was enabled and then disabled at some point for performance reasons.

**Comment by faush01** [comment]
I have added subrip/embeded as a supported subtitle stream type to the latest EmbyCon beta just now. 
Kodi 18 (v1.9.134)
Kodi 19 (v1.10.25)
Give that a try and see how it goes.

**Comment by juanma-cvega** [comment]
Perfect! Now it works without transcoding. Thanks!
