### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by KristupasSavickas** [faush01/plugin.video.embycon#35]
Hello,
I'm trying to connect to my remote emby server, which stands behind a termination proxy which adds ssl on top of emby. I tried with "Use HTTPS" on and off but it doesn't work either way. I also tried ports 80 and 443. The error I'm getting is:
```
12:57:29.142 T:1710330624   DEBUG: EmbyCon.resources.lib.downloadutils (ERROR) -> Unable to connect to [removed] : [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)
```
The proxy is handled by [ngix-proxy](https://github.com/jwilder/nginx-proxy) container (Emby is inside a container as well), and ssl is added with [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion).

From what I understand ngix-proxy redirects requests to a subdomain using the `Host` HTTP header. Looking at the source code it looks like EmbyCon does not set the header and the requests do no get routed as intended.

**Comment by faush01** [comment]
The port will probably be 443 but you need to confirm that in your ngix config.

Try connecting to your emby server remotely using a browser, that will confirm the address, port and SSL cert.

Next use a windows machine with Kodi 17.6 and test with that remotely.

**Comment by faush01** [comment]
I was able to connect to your server and query for the list of users with Kodi and EmbyCon on my windows machine.

Make sure you are using the following:

 - Your server host name
 - Port 443 in port
 - Use HTTPS is turned on

**Comment by KristupasSavickas** [comment]
I'm already using my server from the browser. I'll test it out on Kodi with the changes you suggested later today and will report back.

**Comment by KristupasSavickas** [comment]
There must have been something with the configuration I've been using. I've tried what you suggested and everything works fine. Thanks!
