### ISSUE TITLE
Playlist playback not working as expected

### ISSUE THREAD

**Issue by KristupasSavickas** [faush01/plugin.video.embycon#37]
Hello,
When starting playback from Emby with the "Play on" feature, it always starts from the first song on the playlist, even if I press play on songs other than the first. The same applies to albums.

**Comment by KristupasSavickas** [comment]
I'm running the most recent version of OSMC on Raspberry Pi 3, with EmbyCon 1.5.30.

**Comment by faush01** [comment]
How are you selecting "Play on"
Before selecting Play on what are your navigation steps.

**Comment by KristupasSavickas** [comment]
On the browser:
1. Navigate to an album or a playlist.
2. Press "Play On" button in the top right corner (chromecast icon).
3. Select the device that runs EmbyCon.
4. Play the second song of the album/playlist.

On the device running EmbyCon:
The first song starts playing instead of the first one as expected.

**Comment by KristupasSavickas** [comment]
Also, a bug that might be related: sometimes when playing an album or a playlist playback stops after the first song. Skipping to the second song and going back fixes this.

**Comment by KristupasSavickas** [comment]
The feature I'm referencing as "Play On" is called "Remote Control" on EmbyCon and Emby API documentation.

**Comment by faush01** [comment]
I found the bug when selecting part way through an album starts from the beginning, a fix will be in the next release.

**Comment by faush01** [comment]
you can install the latest beta using the beta repository.

https://embydata.com/downloads/addons/xbmb3c/kodi-beta-repo/repository.beta.emby.kodi-1.0.5.zip

**Comment by KristupasSavickas** [comment]
I've installed the beta and everything works as expected, thanks.
