### ISSUE TITLE
Constantly prompted to select user

### ISSUE THREAD

**Issue by KristupasSavickas** [faush01/plugin.video.embycon#38]
Hi.
I get constantly prompted to select user when using EmbyCon with the "Play On" Emby feature. This usually happens when a song/video ends, but on always. Here's the only error message related to EmbyCon I'm getting, but I don't think it's related:

```
20:53:41.862 T:1707889408   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: bad marshal data (unknown type code)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.embycon/service.py", line 19, in <module>
                                                from resources.lib.websocket_client import WebSocketClient
                                              File "/home/osmc/.kodi/addons/plugin.video.embycon/resources/lib/websocket_client.py", line 7, in <module>
                                                import websocket
                                            ValueError: bad marshal data (unknown type code)
                                            -->End of Python script error report<--
```

Here's what the prompt looks like (sorry a for picture of a screen):
![img_20180815_124656](https://user-images.githubusercontent.com/1362643/44142706-b29d213e-a089-11e8-8040-411f9fac97c7.jpg)

**Comment by KristupasSavickas** [comment]
I'm running the most recent version of OSMC on Raspberry Pi 3, with EmbyCon 1.5.30.

**Comment by faush01** [comment]
The error is an interesting one, you may need to delete your *.pyc files.

https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data

For you they will be in the Kodi path under

/home/osmc/.kodi/addons/plugin.video.embycon/resources/lib/

Delete all the *.pyc file, restart Kodi and try again.

**Comment by faush01** [comment]
As for the login loop I will look into it

**Comment by KristupasSavickas** [comment]
The feature I'm referencing as "Play On" is called "Remote Control" on EmbyCon and Emby API documentation.

**Comment by faush01** [comment]
I can not reproduce the constant log in request issue.

**Comment by KristupasSavickas** [comment]
I've reinstalled kodi and I cannot reproduce this anymore, so I assume my configration must have been corrupt.
