### ISSUE TITLE
Multiple quality selection

### ISSUE THREAD

**Issue by ddurdle** [faush01/plugin.video.embycon#48]
Emby server has introduced multiple server qualities way back in 3.3, but it seems embycon still doesn't have functionality to handle the multiple quality selection dialog.  For instance, on Emby on KODI, when you start a movie or tv show that has multiple versions, it prompts you to select a version to playback.

**Comment by kinv** [comment]
Works fine for me also

**Comment by faush01** [comment]
This feature is already available.
