### ISSUE TITLE
Documentation and releases

### ISSUE THREAD

**Issue by michaelbaudino** [faush01/plugin.video.embycon#51]
Hi there :wave: 

First of all, thanks a lot for your work: I'm using EmbyCon daily and loving it :heart_eyes: 

I'm currently working on integrating EmbyCon into [Recalbox](https://www.recalbox.com) and would love to see some improvements to this already awesome addon:
1. a proper `README` file, documenting:
    * setup/configuration instructions
    * a feature list (and eventually their configuration)
    * differences with [Emby for Kodi](https://github.com/MediaBrowser/plugin.video.emby/wiki/Emby-Repository) addon
    * mentions of [EmbyCon SkinCloner](https://github.com/faush01/script.embycon.skincloner) and [EmbyCon Screensaver](https://github.com/faush01/screensaver.embycon)
    * the releases cycle (as described below)
    * screenshots, maybe?
2. proper versioning/releases, using any combination of those suggestions:
    * simple git tags
    * [GitHub releases](https://help.github.com/articles/creating-releases/) (like you [used to do](https://github.com/faush01/plugin.video.embycon/releases) until v1.1.1)
    * a link to a repository (Kodi addon repository, maybe?) with all versions available
    * a version file, bumped in a dedicated commit
    * semantic versioning (I have no idea what's your current versioning scheme, maybe you are alreay using semver, in which case, please just ignore this)

I read on the main forum thread that "EmbyCon works for [you] and does what [you] need so [you are] reluctant to spend any more time one it", which I totally understand, which is why I'd be happy to submit a PR to create such a `README` file :heart:  (there's not much I can do regarding the releases, though, but if there is, please feel free to let me know).

Thanks again for all the work done, and thanks in advance for this documentation effort :books:

PS: if none of this sounds worth the effort, would you mind pointing me to the latest stable commit, to let me integrate a stable version into Recalbox (using [the code from xbmc/repo-plugins](https://github.com/xbmc/repo-plugins/tree/krypton/plugin.video.embycon) is not handy at all with Buildroot :sweat: and you mentioned beta versions on the forum thread that I don't see there).

**Comment by faush01** [comment]
The main way to use EmbyCon is install it from the main Kodi Repo, the addon info web page links to the main Emby site:
https://emby.media/emby-for-kodi.html
which in turn links to:
https://emby.media/community/index.php?/topic/57016-embycon-kodi-addon/
on that page are some install options and videos on how to install.

The latest released version is always in the master branch, all dev and beta work goes into develop.

Hope this helps.

**Comment by michaelbaudino** [comment]
Thanks for you answer :tophat: 

I always prefer good old README file or Releases to find out what features are provided or which version is the last one (rather than scrolling through a forum thread), but knowing that `master` is always stable helps me a lot, and will at least allow me to integrate it into Recalbox :+1:

**Comment by michaelbaudino** [comment]
Just for information because it may help other people, the latest version in the Kodi repository is [1.7.20](https://github.com/xbmc/repo-plugins/blob/076d6e00cb4c711be7793c4e7f6bd1bd7bf1c628/plugin.video.embycon/addon.xml#L4) (merged in https://github.com/xbmc/repo-plugins/pull/2225/commits/f06530dbe029555467d9aff3d558f144864bd3b7), but it's not on `master` in this repository, only [in `develop`](https://github.com/faush01/plugin.video.embycon/commit/014ae3947bf30ee589bf8ebafe27456982c4b129). Master has version [1.6.19](https://github.com/faush01/plugin.video.embycon/blob/c3b6f5a7f7171a0bf99d3a4219537cc6f6fda30c/addon.xml#L4).

**Comment by faush01** [comment]
Yeah the release management has not really been a priority to be honest.
Based on the feedback and posts in the forum I think there is about 10 users, well that is just a guess.
I will try to be a little more on point when it comes to release time, I really should remember to merge to master for official Kodi repo releases.
They (Kodi) used to have a system where you could link to a tag for them to pull but now it is all done in their repo and makes it hard to track releases.
Anyway I will try to remember to merge to master for the official releases.

**Comment by michaelbaudino** [comment]
Thanks a lot 👌🏽

And yes, having to maintain changes here and in the kodi repository sounds
like a pain 😥

Not sure why they don't use submodules, tbh, rather than forcing all
plugins maintainers to do all that git trickery 🙄

**Comment by faush01** [comment]
I have tagged and created some releases for the last few releases:

- 1.6.19
- 1.7.20

I will continue to do this release new releases. 1.8 is coming up in a few days (Feb Release)

If you want to submit a readme just create a pull request and I will merge it. Documentation is not something I like doing so I avoid it if at all possible.

**Comment by michaelbaudino** [comment]
Here it is: #52

**Comment by faush01** [comment]
Thanks for that, merged.
