### ISSUE TITLE
Can't play .stream files without transcoding

### ISSUE THREAD

**Issue by Dryparn** [faush01/plugin.video.embycon#55]
Hi, I have a problem with playing .strm files.

I have tried these scenarios:

1. Playing .strm stream video through Emby web interface: Works

2. Playing local network video through Emby web interface: Works

3. Playing .strm stream video through Embycon direct http: Not working

4. Playing .strm stream video through Embycon transcode http: Works

5. Playing local network video through Embycon direct http: Works

6. Playing local network video through Embycon transcode http: Works

When i try scenario 3 the screen quickly flicker once and nothing more happens. The Emby server log says the video has been watched.

So emby knows how to play the stream but it's when it passes it to embycon without transcoding that something happens.

I see this in all kodi clients i have, both in linux and windows. It just stopped working. My guess is Embycon has autoupdated, i don't know when really because my kids mostly watch tv or local files.

Emby version: 4.0.2.0
Embycon version: 1.8.16
Kodi version: 18.1

[emby_server.log](https://github.com/faush01/plugin.video.embycon/files/3047734/emby_server.log)
[kodi.log](https://github.com/faush01/plugin.video.embycon/files/3047735/kodi.log)

**Comment by dc95336** [comment]
How about if we change version to 17.6 and ip address to 198.162.0.2:8096/web/home. html

**Comment by Dryparn** [comment]
No change on clean 17.6 Kodi with only embuary.

I can't change IP as i have many services running on that machine. 
172.16.0.0/12 (172.16.0.0 - 172.31.255.255) is a totally valid private address span just like 10.0.0.0/24 and 192.168.0.0/16. It worked great before.

**Comment by Dryparn** [comment]
Also tried Embycon 1.6.19 and 1.7.20 with the same behaviour with no luck. I'm stumped.

**Comment by faush01** [comment]
I will look into this in the next day or so

**Comment by faush01** [comment]
are you able to supply an example of one of your strm files?

**Comment by faush01** [comment]
I have just tested STRM with Direct File Path playback and it is working ok for me.

I was using STRM files with direct paths to media files to test.

**Comment by faush01** [comment]
Also you above log file for Kodi is not showing Direct File Path playback.

**Comment by Dryparn** [comment]
Yeah, sorry, i have been busy. I wrote http in my report above so it must be a misunderstanding. I can't give you the .strm as it contains my login credentials unfortunately.

**Comment by faush01** [comment]
It was the direct play that was not working correct?

Perhaps mock me up a strm with personal details removed but in the same format.

**Comment by Dryparn** [comment]
It's the Direct HTTP that doesn't work.
the contents of the file is in this format: 
http://tv.server.ip:80/movie/myusername/mypassword/26544.mkv

**Comment by faush01** [comment]
Thanks for clarifying, this looks like a Emby Server issue, I will ping the Emby team to see what they think.

**Comment by faush01** [comment]
I have set this up a test:

- STRM pointing to a remote HTTP server (IIS server, file was an MP4 video file)
- Playback in EmbyCon set to Direct HTTP

I am able to play the file back OK using EmbyCon in Kodi.

The Emby team think it might have something to do with redirects on your target server.
Can you try setting up a target on a standard HTTP server and see what happens.

**Comment by faush01** [comment]
This is not an EmbyCon issue.
It is Emby server related but it looks like this is an issue with the HTTP server you are hosting the files on.
I am going to close this now.
