### ISSUE TITLE
"Sort Title" not used

### ISSUE THREAD

**Issue by AFunnyMeme** [faush01/plugin.video.embycon#57]
When browsing movies, Embycon does not use the "Sort Title" field displayed on the server.

![chrome_5NfMfn3M7B](https://user-images.githubusercontent.com/37048134/57186012-80bc6400-6ea5-11e9-86e5-e219b55c42ef.png)
![chrome_bNejmnb1Ot](https://user-images.githubusercontent.com/37048134/57186013-80bc6400-6ea5-11e9-847a-b1046352af1c.png)
![kodi_Eyb3DrjPPv](https://user-images.githubusercontent.com/37048134/57186014-80bc6400-6ea5-11e9-833a-4aef968fda07.png)

Sorting on Embycon does not match that on the Web Browser

**Comment by faush01** [comment]
Looking into this now.

**Comment by faush01** [comment]
This should be working in the latest EmbyCon Beta 1.9.10
