### ISSUE TITLE
ListItem.AudioLanguage isn't filled

### ISSUE THREAD

**Issue by faush01** [faush01/plugin.video.embycon#58]
need to add the info tag to fill in AudioLanguage 

Kodi Info Labels
https://kodi.wiki/view/InfoLabels

**Comment by sualfred** [comment]
It seems that others are additional tracks or subtitles are missing too or are not completely set.

- ListItem.Property(AudioCodec.%i)
- ListItem.Property(AudioChannels.%i)
- ListItem.Property(AudioLanguage.%i)
- ListItem.Property(SubtitleLanguage.%i)

%i = starts with 1. And it seems that only the first one is going to be set, while 2< are not.

**Comment by sualfred** [comment]
Additional info:
These additional properties are only available for ListItem. The video player info labels don't support properties.
In Embuary I use JSON calls to access them via a window(home) prop. So if you want to give support the player info screen for Embuary, the property names are:

- VideoPlayer.AudioLanguage.%i
- VideoPlayer.AudioCodec.%i
- VideoPlayer.AudioChannels.%i
- VideoPlayer.SubtitleLanguage.%i

But that's not required and only if you want.

**Comment by faush01** [comment]
Do you know what InfoLabel is used to set this ListItem.AudioLanguage

> 
> It seems that others are additional tracks or subtitles are missing too or are not completely set.
> 
>     * ListItem.Property(AudioCodec.%i)
> 
>     * ListItem.Property(AudioChannels.%i)
> 
>     * ListItem.Property(AudioLanguage.%i)
> 
>     * ListItem.Property(SubtitleLanguage.%i)
> 
> 
> %i = starts with 1. And it seems that only the first one is going to be set, while 2=< are not.

so only one "extra" one is set using this approach?

**Comment by sualfred** [comment]
ListItem.Audiolanguage is displaying the default track.

So if track 2 of the media is ENG and it is the default one it is used for ListItem.AudioLanguage and ListItem.Property(AudioLanguage.2)

**Comment by sualfred** [comment]
ListItem.Property(SubtitleLanguage.%i) also includes external ones.

**Comment by faush01** [comment]
@sualfred 
OK I think I have ListItem.AudioLanguage sorted out

https://github.com/faush01/plugin.video.embycon/commit/f309ea86a4668a355ed4effb10cde71a95288b19

Now how to I test the
ListItem.Property(AudioCodec.%i)
ListItem.Property(AudioChannels.%i)
ListItem.Property(AudioLanguage.%i)
ListItem.Property(SubtitleLanguage.%i)
When in your skin do the extra audio and subtitle streams show up?

**Comment by sualfred** [comment]
Check the very bottom of a movie info dialog. There are media information shown like the file filename etc.

**Comment by faush01** [comment]
It looks like by default the default one is added to the list already.
This means if I add the default on to the ListItem.Property(AudioCodec.%i) list also it is added twice to the list of available audio tracks at the bottom of the info page.

**Comment by faush01** [comment]
it kind of works in my testing.
I can get it to work with media that has multiple streams but now for ones with just one sub and one audio stream

What does this mean
%i = starts with 1. And it seems that only the first one is going to be set, while 2=< are not.

**Comment by sualfred** [comment]
Hmmm.... it seems that Kodi is already adding ListItem.AudioLanguage to ListItem.Property(AudioLanguage.%i)? If this is true then my statement from above (https://github.com/faush01/plugin.video.embycon/issues/58#issuecomment-501249308) was partly wrong, sry.

**Comment by faush01** [comment]
sorry my bad, I thought I had to add the ListItem properties myself but that is not the case, you mentioned Property(AudioCodec.%i) etc but that is after Kodi does it, you are referring to what the skin sees not what the addon has to do.

In the addon I need to add more stream info items using the ListItem.addStreamInfo and Kodi sets the properties for the addon.

**Comment by sualfred** [comment]
Another day, another thing learned. Makes sense. Good to know.

**Comment by faush01** [comment]
the latest Beta version 1.9.10 should add all the streams with language tags correctly

**Comment by sualfred** [comment]
Tested and works. Thx
