### ISSUE TITLE
Oversaturated/too bright?

### ISSUE THREAD

**Issue by Ninsto** [faush01/plugin.video.embycon#60]
I'm on Windows 10 using Kodi 18, and I've come across a weird issue while watching back 4k. It seems like the brightness is almost at max, i've checked the video file and it's completely normal and if I change the contrast and brightness in my playback settings it does nothing to effect the video. I have a feeling this could be due to it being an HDR file. Image is attached and video info.
Video Info:
```
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Commercial name                          : HDR10
Format profile                           : Main 10@L5.1@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 21 min
Bit rate                                 : 58.1 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.292
Stream size                              : 32.9 GiB (83%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0000 cd/m2, max: 1000 cd/m2
```
![kodi_CZYdP2iQpK](https://user-images.githubusercontent.com/7360618/61053533-125dca00-a431-11e9-8822-bace89ed9122.jpg)

P.S. Other video files which are also HDR look a little bit similar but not as bad.

**Comment by faush01** [comment]
If you bring up the info screen when playing back what is the first word in the overview?

It should be something like directstream or directplay or transcoder.

**Comment by Ninsto** [comment]
> 
> 
> If you bring up the info screen when playing back what is the first word in the overview?
> 
> It should be something like directstream or directplay or transcoder.
DirectStream

**Comment by faush01** [comment]
if you open this file directly with Kodi what happens? Is the video still too bright?

**Comment by Ninsto** [comment]
> 
> 
> if you open this file directly with Kodi what happens? Is the video still too bright?

The same thing. Sorry, must be a Kodi issue

**Comment by faush01** [comment]
yeah sorry, looks like it might be a Kodi issue.
You can post over on the Kodi forum, you might get someone that knows if it is a known issue or not.

**Comment by Ninsto** [comment]
Kodi doesn't parse HDR metadata so I disabled tone-mapping and that fixed it for the most part.
