### ISSUE TITLE
Faster syncing

### ISSUE THREAD

**Issue by prydda** [faush01/plugin.video.embycon#61]
Is it possible to speed up fetching movies? it takes a few minutes to load the movie collection in a poster view. 
My hardware is a coreelec box with amlogic S905x and gigabit internet.

**Comment by faush01** [comment]
How many movies are in your collection?
Is it the list of movies or the artwork that takes all the time?

One option you have is using pages, you can turn this on in the addon settings.

**Comment by prydda** [comment]
2000+ maybe. 
It's when selecting the folder movies, I get a spinning wheel for quite som time and then the artwork is quickly adding up.

**Comment by faush01** [comment]
What version of Kodi are you using?

**Comment by prydda** [comment]
@faush01 latest from coreelec! 

using pages helped alot. Is it possible to sort on year somehow? 👍

**Comment by faush01** [comment]
What version of Kodi are you using?

Unfortunately sorting and paging is not very compatible as the paging is done server side and the sorting is done client side.

**Comment by prydda** [comment]
18.3! 
Oh okay. It's much better now anyways :) cheers

**Comment by faush01** [comment]
I will close this now as there is no actual work to do.
