### ISSUE TITLE
Emby forum thread?

### ISSUE THREAD

**Issue by Haxy89** [faush01/plugin.video.embycon#63]
Hi,

What is going on with this plugin?
Where is official thread in Emby forum?
How to get the newest version working with the newest Emby server and Leia?

Do I miss something?
Some days ago there was a pinned thread in Emby forum.

**Comment by faush01** [comment]
If you are having issues or find a bug you can report it here as a new issue with details.

The pinned thread was not very useful, it was removed.

Is you have questions you can post on the forum, there are lots of users that will help.

**Comment by Haxy89** [comment]
Ok thanks
