### ISSUE TITLE
Embycon Context Menu "Info" doesn't work

### ISSUE THREAD

**Issue by andyxo-xo** [faush01/plugin.video.embycon#64]
As described in this thread here : 
https://emby.media/community/index.php?/topic/76860-two-embycon-context-menu-requests/

Using your superior Embycon context menu, there's no way to see a video files "Info" (codecs etc) in anything other than Embuary "Slide View" using a Firestick because its remote doesn't have any seperate buttons to do that. Starting with Embycon v1.9.30 you implemented a context menu for info labeled "Info" but when selected nothing at all happens. If you could get your added Info selection to work that would be awesome and your context menu would rock on the Firestick :-)

Cheers

**Comment by faush01** [comment]
The Info menu item is bringing up the Info Dialog for me on all my media.
Can you test using the default skin.

**Comment by andyxo-xo** [comment]
Sure enough you are right, it does work on the default Leia skin Estuary. Is there something you could advise sualfred on to make it work on his Embuary skin too by chance?

**Comment by faush01** [comment]
Try Beta version 1.9.33

**Comment by andyxo-xo** [comment]
Greets, just tested 19.3.4 and your "Info" context menu item now works great on TV Shows & Movies and also on the Continue Watching widget I tested...  super awesome and thanks :-) . Only files it doesn't work on are those located in my Home Videos & Photos library... is that by design?

(Will test the sleep time lost issue tomorrow morning)

**Comment by faush01** [comment]
Try those files using the default skin to see what happens.
I think now it should work on all files and media that it can work on, if it is not working now it is not a context menu issue but probably a media details issue.
Closing this now
