### ISSUE TITLE
Continue Watching disappears (time position lost) if have to wake hard drive

### ISSUE THREAD

**Issue by andyxo-xo** [faush01/plugin.video.embycon#65]
As explained more in depth in this thread (and Kodi log posted there):
https://emby.media/community/index.php?/topic/77054-continue-watching-disappears-time-data-lost-if-have-to-wake-hard-drive/

If my external hard drives are asleep and I try to play a partially played video (whether from a library or Continue Watching widget) that's located on the asleep external hard drive, the video will not play, the time saved position will be lost, and the file will disappear from the Continue Watching widget. Next time the video is played, now that the external has woken up, the video will only play from the beginning (time position saved is lost).

Cheers

**Comment by faush01** [comment]
I will need to try to set this up in a reproducible test environment.
I can see from the log how this might happen but I need to be able to reproduce it to try to fix it.
Perhaps a removable USB thumb drive will emulate the sleeping drive issue.

**Comment by faush01** [comment]
Try beta build 1.9.34

I have extended the time out of the playback resume task to 2 minutes.
If this does not work I will need to rework some of the playback logic which is going to take some time.

**Comment by andyxo-xo** [comment]
Hi, worked great today and thank you :-)

Will let you know if in the future it happens again...

**Comment by andyxo-xo** [comment]
Hello again faush01, this problem has started again in the past two days. Funny thing is that I updated absolutely nothing. I didn't update the Emby server and absolutely nothing on Kodi. Do you have any idea why this could have started again after working great since 8 Sep? Seems like after one month it reverted back to previous behavior....

**Comment by faush01** [comment]
There has been no changes in this sine the last one.
The main problem is the server is taking a long time to start streaming the content, the original time out as 15 seconds, I increased that to 2 minutes, if your server is taking longer than 2 minutes then you might have other issues.

**Comment by andyxo-xo** [comment]
Thanks for your reply. Hmmm weird. Well, all I can provide is that nothing at all has changed on my end, same hard drive/computer and all. The behavior is that the time between pressing play on the partially played vid and then the time that I lose that vid's time position is around 30 seconds... so it's not waiting a full 2 minutes to "reset itself" back to an unplayed initial state. Has happened exactly today and yesterday while working beautifully for one month straight. Like I said, so very strange :-(
