### ISSUE TITLE
Embycon not playing video playlists

### ISSUE THREAD

**Issue by caconym64** [faush01/plugin.video.embycon#67]
When a playlist of videos/films (or music) has been created in Emby Media Server, Embycon sees the playlist ok, but it doesn't 'play' the playlist, it just opens it as a list of videos (or music tracks). You then need to play each individually, they don't automatically play after each one as expected.

(This is using either LibreElec or OSMC on Raspberry Pi - basically using the Kodi video addon.)

**Comment by faush01** [comment]
I will add a new entry in the Context menu to "Play All" when you select a Playlist.

**Comment by caconym64** [comment]
That would work - thank you :)

**Comment by faush01** [comment]
Beta 1.9.37

The latest beta has a new context menu item that lets you play all items in a playlist.

**Comment by caconym64** [comment]
Works well thanks. You can mark this issue resolved for me.
