### ISSUE TITLE
add Year as submenu

### ISSUE THREAD

**Issue by prydda** [faush01/plugin.video.embycon#71]
Can this be added to embycon also? 

https://github.com/MediaBrowser/plugin.video.emby/issues/307

https://github.com/MediaBrowser/plugin.video.emby/commit/49135ca342100bcdb7eef5cbbd06e070df830e4b

**Comment by faush01** [comment]
I have added Year, Decades and Tags to the main EmbyCon menu for library and global list item for movies.

**Comment by faush01** [comment]
This is now in the latest beta
