### ISSUE TITLE
sorting in all movies

### ISSUE THREAD

**Issue by prydda** [faush01/plugin.video.embycon#73]
When I'm opening "All TV Shows, Tv shows - EmbCon" I've a nice sorting list with A-Z and I can just scroll through all content. 
While on "All Movies, Movies - EmbyCon" I'm only getting 100 videos and no sorting list, can you possible add it? 👍

**Comment by faush01** [comment]
How are you opening this?
Using a Skin or going directly to the Add-on menu?

**Comment by prydda** [comment]
using embuary and talking about the widgets at the top.

**Comment by faush01** [comment]
I think that might be a skin question, you should ask in the embuary  skin forum
https://emby.media/community/index.php?/topic/49724-support-thread-embuary-a-emby-kodi-skin/
