### ISSUE TITLE
If (Optional) Shared network folder in Emby ends with a slash (\) ... direct playback does not work

### ISSUE THREAD

**Issue by zkutasi** [faush01/plugin.video.embycon#74]
HI,

I have found a little irk...
If the alternative path in EMby for (Optional) Shared network folder ends with a slash, the path substitution algorithm also tries to replace that with smb://, like this (found in the logs)

00:42:32.294 T:140701624090560 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
00:42:32.294 T:140701624090560   ERROR: Playlist Player: skipping unplayable item: 3, path [smb://Synology216/music/EPssmb://Kobosil - ----- (2013 - Unterton)/04. Kobosil - Herschel.flac]

Notice the two "smb://" in the path...
I think the substituter should only replace the first occurrence, not all of them, or it should replace in the front only...
Took me 1 hour with reading the source code to find this...

**Comment by faush01** [comment]
Try the latest beta 1.9.47

**Comment by zkutasi** [comment]
Thanks, looks fine now.
