### ISSUE TITLE
Remote controlling from browser shows Volume slider at Zero

### ISSUE THREAD

**Issue by zkutasi** [faush01/plugin.video.embycon#75]
Hi guys,

I just have noticed, that if I play anything from Firefox or Chrome (latest on both) and I "Play on another Device" and select EmbyCon (I have Kodi on a separate HTPC) then in the browser, the volume remains at Zero, actual volume is non-0 though, and I can adjust it with the slider and the volume changes on the HTPC system, but it jumps back to Zero in the browser every time.

Is this a bug or expected?
 
Kodi from Debian (17.6 Debian package version: 2:17.6+dfsg1-1ubuntu1)
EmbyCon 1.9.32
Emby 4.3.0.26

Thanks...

**Comment by faush01** [comment]
try the latest beta

**Comment by zkutasi** [comment]
Thanks, switched to the beta repo for now (when do you intend to do a next stable in the Kodi repo?), and now it is OK, although it is a bit slow (the change I mean), but much better.

**Comment by faush01** [comment]
I expect the next stable will be in a few days, perhaps the weekend.
Yeah the change is slow as the update is only send every 10 seconds. So you change it and then emby sets it back to where it was and then when the next update happens in 10 seconds it updates to where you set it. I think this is just how emby works from what I can tell.
