### ISSUE TITLE
Issue with Emby channel

### ISSUE THREAD

**Issue by ifurman68** [faush01/plugin.video.embycon#76]
I wrote Emby plugin to play some HTTP Live Streamings. The plugin works everywhere, but in EmbyCom. I'm not familiar with Kodi plugins dev, but comparing Emby server' working and not working (EmbyCom) logs, I noticed that the server seems to require SegmentContainer param in play url, otherwise ffmpeg fails. After I added the following line:

"&SegmentContainer=ts" +

to %AppData%\Kodi\addons\plugin.video.embycon\resources\lib\utils.py (between lines 102-103), everything started working. The playurl now is:

             playurl = ("%s/emby/Videos/%s/master.m3u8" +
                       "?MediaSourceId=%s" +
                       "&PlaySessionId=%s" +
                       "&VideoCodec=h264" +
                       "&AudioCodec=ac3" +
                       "&MaxAudioChannels=6" +
                       "&deviceId=%s" +
                       "&VideoBitrate=%s" +
                       "&SegmentContainer=ts" +
                       "&maxWidth=%s")

I don't know if that's a correct fix, but you see the problem.

These are the examples of URLs playing the same item:

EmbyCon (not working):
live.m3u8?MediaSourceId=xxxx&PlaySessionId=xxxx&VideoCodec=h264&AudioCodec=ac3&MaxAudioChannels=6&deviceId=xxxx&VideoBitrate=6400000&maxWidth=1920&api_key=xxxx

Emby Web client (working):
live.m3u8?MediaSourceId=xxxx&PlaySessionId=xxxx&VideoCodec=h264,mpeg2video,hevc&AudioCodec=ac3,mp3,aac&VideoBitrate=139808000&AudioBitrate=192000&TranscodingMaxAudioChannels=6&**SegmentContainer=ts**&SegmentLength=3&MinSegments=1&BreakOnNonKeyFrames=True&hevc-profile=Main,Main10&h264-level=51&DeviceId=xxxx&api_key=xxxx

Thanks

**Comment by faush01** [comment]
From what I can see this should not be required. The default SegmentContainer is already TS so it should not have to be set.

Can you supply a log with the failed message from Emby server.

**Comment by ifurman68** [comment]
Where do you see that? I looked at MediaBrowser sources on github and yes, it suppose to default to TS. But, as I understand, the open source is outdated and something changed in the new Emby Server and it does not default to TS anymore (maybe, it's a server bug, I notified Luke already).

Here's a server log:

	*** Error Report ***
	Version: 4.3.0.30
	Command line: ****\AppData\Roaming\Emby-Server\system\EmbyServer.dll
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///****/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
	Processor count: 8
	Program data path: ****\AppData\Roaming\Emby-Server\programdata
	Application directory: ****\AppData\Roaming\Emby-Server\system
	System.Exception: System.Exception: Error starting ffmpeg
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.BaseHlsService.ProcessRequest(StreamRequest request)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()

Here's ffmpeg command generated by the server (notice -segment_format is empty!):

`ffmpeg.exe -loglevel +timing -i "https://****.com/****.m3u8" -map_metadata -1 -map_chapters -1 -threads 0 -sn -c:v:0 libx264 -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -pix_fmt yuv420p  -maxrate 6400000 -bufsize 12800000 -preset veryfast -profile:v:0 high -level:v:0 4.1 -crf 23 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" -vsync -1 -codec:a:0 ac3 -disposition:a:0 default -ac:a:0 6  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format  -segment_write_temp 1 -segment_list_entry_prefix "hls/****/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "****.m3u8" -y "****.ts"
`

Here's ffmpeg error:

10:55:04.395 Output #0, segment, to '1':
10:55:04.395 Output file #0 does not contain any stream

**Comment by faush01** [comment]
Yes I can see it is set to: 
-segment_format mpegts 
with my trans-code requests. Coul dit have somethign do to with the fact you are transcoding a remove file:
-i "https://****.com/****.m3u8"
Can you try a local file and see if that makes a difference.
I think this might be a bug in the Emby Server.

**Comment by ifurman68** [comment]
I agree on that might be a server bug, but until it's fixed the workaround I mentioned in the original post does the trick.

**Comment by faush01** [comment]
this will be in the next beta release
