### ISSUE TITLE
Selection of audio sreams and subtitles don't work

### ISSUE THREAD

**Issue by ifurman68** [faush01/plugin.video.embycon#77]
When a movie has multiple audio and subtitle streams selecting any of them does not make any difference. The plugin always plays the default streams no matter what was selected.
As a side note: selection is available only at the movie's startup. During playing the selection of streams (both audio and subtitle) is disabled in configuration menu  

Emby Server v4.3.0.30 (both Ubuntu and Windows)

**Comment by faush01** [comment]
There was bug in the audio and subtitle selection that was stopping the selected audio and subtitle stream from being passed to emby when transcoding, should be fixed now, try the latest beta 1.9.49.

Only one audio and subtitle stream is available when you transcode your source material.
You need to stop and restart the transcode with new options if you want to change.
Direct Streaming should allow you to switch in the Kodi client without restarting playback.
