### ISSUE TITLE
Users list screen always appears

### ISSUE THREAD

**Issue by fallais** [faush01/plugin.video.embycon#78]
Hello,

Thanks for your work with this plugin that is very useful !
I am facing an issue with the users list that appears all the time, the session should be saved once logged in, shouldn't it ?

Thanks.

**Comment by fallais** [comment]
I did not see the #66, clearly my issue but I installed the plugin recently, it should be fixed right ?

**Comment by faush01** [comment]
yes it will be saved but by default the user selection screen will pop up when the screen saved is dismissed. This can be changed in the settings.

EmbyCon -> Settings -> Events -> Screensaver -> Show change user dialog.

**Comment by fallais** [comment]
Thanks, closing this.
