### ISSUE TITLE
Problem with large favourite list!

### ISSUE THREAD

**Issue by FilmjunkieGF** [faush01/plugin.video.embycon#79]
Hello,

in v1.9.47 the favourite section was removed and added back in v1.9.48 since then there is this critical issue:

When opening a large favourite list (>1000 items) the Emby Server (Linux) gets unreachable/unusable for 10-15 minutes.
I hope you can look into this and bring a fix.

**Comment by faush01** [comment]
I only moved the link, it still works the same way it always has.

What happens if you view the playlist using the web client?

This sounds like a server issue.

**Comment by FilmjunkieGF** [comment]
ok, I checked this issue again. The entry came back with 1.9.46? Since then I get this problem. Before that I did not have this issue. 
No problems when opening it in Web-Browser.
There are 1165 items in the list. Is this too much?

**Comment by faush01** [comment]
I can confirm this bug, I am looking into it now.

**Comment by faush01** [comment]
Beta 1.9.50 should fix this issue, please test and confirm if possible, thanks.

**Comment by FilmjunkieGF** [comment]
Yes, it is working now! Thanks for you great and fast support!
