### ISSUE TITLE
Actor are not shown in Movie-Information Panel

### ISSUE THREAD

**Issue by scrimpy** [faush01/plugin.video.embycon#80]
Guess since the latest Emby update, Embycon is not showing actors in the movie-information panel of Kodi anymore.
Please let me know which log files you need to have.

**Comment by faush01** [comment]
Did you turn on "Include people" in the EmbyCon settings?
By default this is off.

EmbyCon -> Settings > Iterface -> Include people

**Comment by scrimpy** [comment]
Sorry for late response. Yes that worked, thank you.
When I hit enter on the actor, I get the emby context menu and not the actor information and other movies with this actor in the libary. Is this related to embuary theme?

**Comment by faush01** [comment]
it might be skin related, if you are using the embuary skin you should post over on the embuary skin forum:

https://emby.media/community/index.php?/topic/49724-support-thread-embuary-a-emby-kodi-skin/
