### ISSUE TITLE
Emby broken in Kodi

### ISSUE THREAD

**Issue by johnkjaer** [faush01/plugin.video.embycon#82]
![image](https://user-images.githubusercontent.com/58855856/70810848-c985b500-1dc4-11ea-95ad-74e0a361037d.png)
Emby broken in Kodi

**Comment by johnkjaer** [comment]
It is Kodi who need to update the revision. By using the plugin from here the problem is solved.

**Comment by faush01** [comment]
Please use the add-on repositories available form the link in the notification to get that latest version:

http://kodi.emby.media/
