### ISSUE TITLE
Version difference in Kodi Addon

### ISSUE THREAD

**Issue by ViXXoR** [faush01/plugin.video.embycon#84]
I noticed there was an update for the add-on in the Kodi repository, but there has been no release here for 8 months. The version in the Kodi repository is also 1.9.33, which seems strange. Is that an official release that just isn't published on GitHub yet?

**Comment by faush01** [comment]
I dont keep the github releases updated, I keep on forgetting and eventually just gave up.

**Comment by ViXXoR** [comment]
So the Kodi Addon version is the latest?

**Comment by faush01** [comment]
The latest version is available form here:
http://kodi.emby.media/

**Comment by greymda** [comment]
> The latest version is available form here:
> http://kodi.emby.media/

is it possible to downgrade to prior version? now i am constantly getting `ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 500` and it doesn't play anything...

**Comment by faush01** [comment]
There are some older versions here

https://github.com/faush01/plugin.video.embycon/releases

or for some recent releases here:

https://embydata.com/downloads/addons/xbmb3c/multi-repo/beta-krypton/plugin.video.embycon/

Replace the files on your system with the ones from the zips.

The error you are seeing is from the server though.

**Comment by greymda** [comment]
thank you, and YES, you were right - it was server error.

**Comment by prydda** [comment]
Check out https://github.com/release-it/release-it - If you want to keep releases tab in sync 📦

**Comment by faush01** [comment]
cool I will check that out.
