### ISSUE TITLE
Enable https for kodi repository

### ISSUE THREAD

**Issue by RamonEbdon** [faush01/plugin.video.embycon#85]
Hi there,

I've just gone to install the Emby repository into Kodi, but noticed the download links all used plain http connections to kodi.emby.media. Out of curiosity, I tried a https connection and got a warning about a certificate belonging to connect.mediabrowser.tv that expired in 2016 :)

Since you've got a wildcard cert for *.emby.media, it couldn't hurt to use that on the kodi repository download server too, just to be on the safe side? The addon itself appears ok with using all https connections to embydata.com, just the download page isn't protected.

Cheers 👍

**Comment by faush01** [comment]
Hi,
I don't maintain the Emby servers but I will pass this on to the Emby team.
Thanks

**Comment by faush01** [comment]
Try this site, it is going to be the new address going forward:

https://kodi.emby.tv/

**Comment by RamonEbdon** [comment]
Great, thanks :)
