### ISSUE TITLE
EmbyCon not showing up in Play On Devices List

### ISSUE THREAD

**Issue by ramon-kramer** [faush01/plugin.video.embycon#86]
hey guys, i'm running emby server as latest docker (4.2.1.0) with apache reverse proxy. everything runs fine in browser, kodi via embycon (1.9.54) & android app, except that the embycon device is not shown in the play on list. it still appears in devices (server settings) and also activities are logged fine. play on with android device is working.

any ideas?

**Comment by faush01** [comment]
make sure under the EmbyCon addon settings in the services tab that "Enable emby remote control" is enabled.

If it is already it could be an issue with your reverse proxy and WebSockets.
Try to connect to the Emby Server not using the reverse proxy and see if that works.

**Comment by ramon-kramer** [comment]
you're right, i found the issue in websockets. thanks!
