### ISSUE TITLE
Emby libraries with "mixed content" and "audiobook" not available in EmbyCon

### ISSUE THREAD

**Issue by Larx** [faush01/plugin.video.embycon#90]
Subject says it all: I want to switch from the heavyweight addon to EmbyCon. I notice that one of my libraries containing mixed (tv shows and movies) and both "audio books" (don't know the exact description in english) libraries are not available in EmbyCon. They were available in the original Emby addon.

**Comment by faush01** [comment]
Kodi does not handle "mixed" content well, Kodi is designed to show Movies or TV Shows separately, they do not map well to views or display well when mixed together when using an add-on. For this reason mixed content is not supported.

I am not sure about audio books, kodi does not feel like a good audio book player, it lacks a lot fo the features audio book players should have like robust resume, speed adjustments, proper chapter control etc.

**Comment by Larx** [comment]
Thanks for the quick reply.

My "mixed library" contains both TV series and movies. The original addon handles this at the moment by creating two library nodes for this library, appended by "(series)" and "(movies)" respectively. This seems like a good solution for me.
(BTW: Until a few days ago, when I once again had to rebuild the library because the original Emby-for-Kodi addon did no longer find the content it should play for unknown reasons, there was only one library node appended by "dynamic"?!?! This gave only a reduced functionality in Kodi. However, not an EmbyCon problem.)

Concerning the audio books: Kodi works quite well for me for the children's stories. However, I use direct access to the files via network and the native Kodi functionality. On Android clients I use the Emby client. Probably a very reduced use case for the audio book library type, I know, but it works well this way. I just wanted to "unify" the experience on all devices. Not a priority, however ;-).

**Comment by faush01** [comment]
Yeah it splits them up into Movies and Series as Kodi does not display mixed content well.
The best way would be to have two different libraries one for the movies and one for the serires 
Why do you need them in the same library?

**Comment by Larx** [comment]
Well, obviously it's possible to split up the library. However, I"ve used it this way for years, and it works well in other Emby client apps, therefore I asked.
E.g. one of my mixed libraries is documentaries. Here I don't mind or even know if a title I'm searching for is part of a series or a movie, so having all documentaries in one library makes sense - for me.
If I split up the library in order to be able to use it Kodi, it will also be split up in any Emby client app which will defy my sense of order ;-) .
So - not really a severe problem, but a nice-to-have feature, if EmbyCon would provide the content of mixed libraries at least split up into the different content types.

**Comment by faush01** [comment]
ok I understand but unfortunately I don't currently have any plans to add mixed libraries at the moment.

**Comment by Larx** [comment]
Ok, I understand.
