### ISSUE TITLE
set default view

### ISSUE THREAD

**Issue by prydda** [faush01/plugin.video.embycon#91]
make the default view to set the view once and not always? 

Scenario: 
I set the default view as grid (this is what I want 99% of the time) but when I jump to live TV section I want to have a list so I can see what game is on rather then title: "Hockey" for example. When I change this view to list and then go back to live tv it's grids again.

**Comment by faush01** [comment]
once you set the default view for a type of item then that view is used for ALL pages of items of that type.
I can not think of a way around this.

**Comment by prydda** [comment]
Can I reset the default view somehow, reset the whole addon? 
Realized everything does not look good in poster view..

**Comment by faush01** [comment]
Yes this needs to be added, I will reopen this issue and track the work here.

**Comment by faush01** [comment]
in the latest beta you can set and unset the default view from the context menu
you can also wipe all default views using the settings page, go to the default view tab in the add-on settings and select Defaults.

**Comment by prydda** [comment]
Thanks! Was able to reset the default view 👍
